[theme]
theme = "bad-wolf"

[icons]
icons = "awesome6"




[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%H:%M')"

[[block]]
block = "battery"
format = "$icon $percentage"

[[block]]
block = "memory"
format = "$icon $mem_used_percents"

[[block]]
block = "temperature"
interval = 2
format = " $icon $average"
chip = "coretemp-isa-0000"

[[block]]
block = "keyboard_layout"
driver = "xkbevent"

[block.mappings]
"us" = "EN"
"ru" = "RU"
